ROUTINE Community [Type=INC]
#Define Server "https://community.intersystems.com/"
#Define MainTags "Caché,Ensemble,DeepSee,HealthShare,iKnow,Atelier,Online Learning,Documentation,InterSystems IRIS,Open Exchange,Global Masters,Worldwide Response Center (WRC),Global Summit,Developer Community,Other,DC Feedback"
#Define PublicTags "Caché,Ensemble,DeepSee,HealthShare,iKnow,Atelier,Online Learning,InterSystems IRIS,Open Exchange,Worldwide Response Center (WRC),Global Masters,Documentation" 
